version: '2'

services:
  db:
    build: ./db/
    volumes:
      - data:/var/lib/postgresql/data

  quest:
    build: .
    ports:
      - "8000:8000"
    links:
      - db

volumes:
  data:
    driver: local
