# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 05:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.CharField(max_length=20, verbose_name='Группа'),
        ),
    ]
