# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160506_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroku_url', models.CharField(default='', max_length=200)),
                ('github_url', models.CharField(default='', max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(default='', max_length=12, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
